app_service_name = "my-java-app-xvdsv"
runtime         = "JAVA|11"
storage_account_name = "chirustorageaccount"
subnet_address_prefix = ["10.0.1.0/24"]
resource_group_name = "american-lines-resources"
location = "East US"
vnet_address_space = ["10.0.0.0/16"]
container = "chiru-test-storage-container"
subnet_name = "chiru-test-subnet"
vnet_name = "chiru-test-vnet"